### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by darky** [xialvjun/ts-sql-plugin#18]
@xialvjun, can you please activate in settings *actions*
I will play with it in *github-actions* branch
Would be amazing to have CI in **ts-sql-plugin** repo :rocket:

**Comment by xialvjun** [comment]
![image](https://user-images.githubusercontent.com/4413712/82179824-d1b4c400-9911-11ea-8226-e8aa53ff4a21.png)
How ? I don't understand devops very well.

**Comment by darky** [comment]
Seems it ok on screenshot! Thanks! I check it later :)

**Comment by darky** [comment]
Great! It works! Thanks 👍
