### ISSUE TITLE
How to generate many OR clauses from array with same field

### ISSUE THREAD

**Issue by darky** [xialvjun/ts-sql-plugin#2]
For example, I have array of values, which should be `like`

```typescript
const someArray: string[] = ['val1', 'val2', ..., 'valn'];
```

Need to generate sql like:

```
someArray.map(v => `field LIKE '${v}%'`)
```

How to do it with **ts-sql-plugin**?

Maybe need some helper like `sql.or` ?
But trouble, that field name is equal in all clauses.

**Comment by xialvjun** [comment]
`sql.or` is good:   `sql.or([{ 'field1 like': v1 },{ 'field2 like': v2 },])`...

and the type info is: `sql.or(({'field1 like': string} | {'field2 like': string})[])`

With this type info, I can generate sql `field1 like xxx or field2 like yyy`.

I'll make it as soon as possible.

**Comment by xialvjun** [comment]
Sorry for too long no reaction. I was engaging in my full time job.

Now it's done in https://github.com/xialvjun/ts-sql-plugin/commit/c0964fa21fc08e514ce9711c4c118a1b151a7e30
