### ISSUE TITLE
increase cli performance

### ISSUE THREAD

**Issue by darky** [xialvjun/ts-sql-plugin#29]
@saxumcordis FYI

**Comment by xialvjun** [comment]
Hey, @darky I found two ready to use type safe sql builder https://github.com/juanluispaz/ts-sql-query/ and https://github.com/Ff00ff/mammoth .
I don't know if `ts-sql-plugin` is still usefull compared to those two.
I'm happy that `ts-sql-plugin` was usefull to you.
I don't know how to express it, I just use `ts-sql-query` in my new project.
Of course you can still choose `ts-sql-plugin`, you can use it, modify it or whatever, but....
Whatever, this is just an introduction of `ts-sql-query` and `mammoth`.
If needed, I can delete this comment.

**Comment by darky** [comment]
@xialvjun thanks for suggestions) 
I investigate it later, but at first glance seems it query builders with their disadvantages
https://gajus.medium.com/stop-using-knex-js-and-earn-30-bf410349856c
