### ISSUE TITLE
Syntax error in Windows

### ISSUE THREAD

**Issue by rammlied595** [xialvjun/ts-sql-plugin#3]
`ERROR:  syntax error at or near "$"` in

` let buffer_rs = child_process.execSync(
              ${config.command} $'EXPLAIN ${s}',
            );`
I did not found way to feed CMD multiline argument :(

**Comment by xialvjun** [comment]
Sorry for too long no reaction, I was engaging my full time job.

I've remove the `$` in `psql -c $'EXPLAIN SQL'`, it should be help to run command in windows. I don't have a windows environment, can not test it. Hope for reply.

**Comment by rammlied595** [comment]
no need to remove `$` 
it will not help )
it can be resolved by executing child process with another shell. probably it can be fixed by enviroment variables (comspec)

**Comment by xialvjun** [comment]
I'm going to replace `execSync` with `spawnSync` which accepts more formal command and args pattern, it should help.

**Comment by rammlied595** [comment]
`cross-env COMSPEC="C:\Program Files\Git\bin\bash.exe"  ts-sql-plugin -p . -c "psql -c"`
works! 
with current code

**Comment by xialvjun** [comment]
v0.4.0 has using spawnSync...
change tsconfig to
```js
"plugins": [
      {
      "name": "ts-sql-plugin",
      "command": ["docker", "exec", "6b8204b88af5", "psql", "-U", "postgres", "-c"],
      }
    ]
```

and the cli is
```shell
ts-sql-plugin -p ./my_ts_project docker exec 6b8204b88af5 psql -U postgres -c
```
