### ISSUE TITLE
sql.mock

### ISSUE THREAD

**Issue by darky** [xialvjun/ts-sql-plugin#4]
Would be good to have universal `sql.mock` method for resolving any problem.
Example: 

```sql
SELECT ${sql.mock('*', entityToFields())} FROM test
```

First argument is passed to ts-server, second to runtime

**Comment by darky** [comment]
Also this can help with #2 problem too

**Comment by xialvjun** [comment]
`sql.mock` is not bad, just like `eslint ignore line`, but what does it do? I mean in `` sql`select ${sql.mock('*', entityToFields())} from test` ``, what's `entityToFields()`?

I need more concret scene. Leave this issue open when people came up with a concret scene.

**Comment by darky** [comment]
`sql.mock` should simply return second argument.
Example:

`select ${sql.mock('*', 'user_name')} from users`
return `select * from users` to tsserver static compilation
return `select user_name from users` to runtime

**Comment by darky** [comment]
fixed here https://github.com/xialvjun/ts-sql-plugin/pull/10
