### ISSUE TITLE
ts-sql-plugin cli broken on 0.3.6

### ISSUE THREAD

**Issue by darky** [xialvjun/ts-sql-plugin#5]
Simple sql clause: `sep.pm_data_type like 'decimal%'` not working.
Error:

```
ERROR:  syntax error at or near "\"
LINE 37:                or sep.pm_data_type like \decimal%'
                                                 ^
/bin/sh: -c: line 37: syntax error near unexpected token `)'
/bin/sh: -c: line 37: `            )'
```

**Comment by xialvjun** [comment]
How do you write your code? 
I test `` sql`select * from books where ${sql.or([{'title like': 'xxx%'}, {title: 'yyy'}])}` `` is ok.

**Comment by darky** [comment]
Can you try please:
`select * from books where title like 'xxx%'`

**Comment by xialvjun** [comment]
now v0.4.0 using `child_process.spawnSync` resolved this problem.

see https://github.com/xialvjun/ts-sql-plugin/issues/3#issuecomment-559760702

**Comment by darky** [comment]
Thanks
