### ISSUE TITLE
Not working with postgres 12 

### ISSUE THREAD

**Issue by darky** [xialvjun/ts-sql-plugin#6]
psql: error: could not connect to server: FATAL:  unsupported frontend protocol 1234.5679: server supports 2.0 to 3.0

**Comment by xialvjun** [comment]
Use a newer version of psql or use any other command line sql client.
I've tried docker image `postgres:12-alpine` and use psql in that image, things is ok.

**Comment by darky** [comment]
This situation occured with standalone psql on OS X.
Ok, I try psql from `postgres:12-alpine`
